spring:
  application:
    name: rchive

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Seoul

  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'  # SQL? ???? ??
        show_sql: 'true'    # sql ??
        highlight_sql: 'true'   # SQL? ? ??
    hibernate:
      ddl-auto: update

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    tags-sorter: alpha
#    operations-sorter: method
#    doc-expansion: none