spring:
  application:
    name: rchive

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jackson:
    time-zone: Asia/Seoul

  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'  # SQL? ???? ??
        show_sql: 'true'    # sql ??
        highlight_sql: 'true'   # SQL? ? ??
    hibernate:
      ddl-auto: update
