services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        JAR_FILE: rchive-back-${VERSION}.jar
    image: rchive-${VERSION}
    ports:
      - "8080:8080"
    container_name: rchive-api-${VERSION}
    restart: unless-stopped
    environment:
      - VERSION=${VERSION}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge